apiVersion: v1
kind: ConfigMap
metadata:
  name: l4s-lidar-sender-config
  namespace: l4s-lidar
  labels:
    app.kubernetes.io/name: l4s-lidar-sender
data:
  LOG_LEVEL: "info"
  DEFAULT_FRAME_RATE: "10"
  DEFAULT_TOPIC: "/husky/ouster/points"
  NOTE: "All runtime parameters may be overridden by run_k8s.sh"
