apiVersion: v1
kind: Secret
metadata:
  name: l4s-lidar-common-secret
  namespace: l4s-lidar
type: Opaque
data:
  # Example (generate with: echo -n "value" | base64)
  # API_TOKEN: ""
  # SHARED_PASSWORD: ""
