# ================================
# Pointcloud image (on top of minimal)
# ================================
FROM ghcr.io/achilleas2942/l4s-ros:minimal

ENV DEBIAN_FRONTEND=noninteractive

# ================================
# ROS2 PointCloud runtime deps
# ================================
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-rolling-sensor-msgs \
    ros-rolling-std-msgs \
    ros-rolling-rclcpp \
    ros-rolling-rclpy \
    python3-numpy \
    python3-yaml \
    python3-pip \
    tmux \
    && rm -rf /var/lib/apt/lists/*

# ================================
# Draco (Python bindings)
# ================================
RUN pip install --no-cache-dir --break-system-packages DracoPy

# ================================
# Entrypoint
# ================================
COPY entrypoints/entrypoint_pointcloud.sh /entrypoint_pointcloud.sh
RUN chmod +x /entrypoint_pointcloud.sh

ENTRYPOINT ["/entrypoint_pointcloud.sh"]
CMD ["bash"]
