apiVersion: v1
kind: ConfigMap
metadata:
  name: l4s-lidar-receiver-config
  namespace: l4s-lidar
  labels:
    app.kubernetes.io/name: l4s-lidar-receiver
data:
  LOG_LEVEL: "info"
  RECEIVER_MODE: "standard"
