apiVersion: apps/v1
kind: Deployment
metadata:
  name: l4s-lidar-receiver
  namespace: l4s-lidar
  labels:
    app.kubernetes.io/name: l4s-lidar-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: l4s-lidar-receiver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: l4s-lidar-receiver
    spec:
      serviceAccountName: l4s-lidar-receiver
      containers:
        - name: l4s-lidar-receiver
          image: ghcr.io/achilleas2942/l4s-ros:pointcloud
          imagePullPolicy: Always
          command: ["bash"]
          args: ["/opt/pointcloud/receiver_scripts/receiver.sh"]
          tty: true
          stdin: true
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: l4s-lidar-receiver-config
                  key: LOG_LEVEL
            # Secret envs (values created by run_k8s.sh)
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: l4s-lidar-common-secret
                  key: API_TOKEN
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: l4s-lidar-common-secret
                  key: PASSWORD
          ports:
            # UDP ports 30112–30119
            - containerPort: 30112
              protocol: UDP
            - containerPort: 30113
              protocol: UDP
            - containerPort: 30114
              protocol: UDP
            - containerPort: 30115
              protocol: UDP
            - containerPort: 30116
              protocol: UDP
            - containerPort: 30117
              protocol: UDP
            - containerPort: 30118
              protocol: UDP
            - containerPort: 30119
              protocol: UDP
            # UDP ports 51000–51009
            - containerPort: 51000
              protocol: UDP
            - containerPort: 51001
              protocol: UDP
            - containerPort: 51002
              protocol: UDP
            - containerPort: 51003
              protocol: UDP
            - containerPort: 51004
              protocol: UDP
            - containerPort: 51005
              protocol: UDP
            - containerPort: 51006
              protocol: UDP
            - containerPort: 51007
              protocol: UDP
            - containerPort: 51008
              protocol: UDP
            - containerPort: 51009
              protocol: UDP
          volumeMounts:
            - name: receiver-scripts
              mountPath: /opt/pointcloud/receiver_scripts
              readOnly: true
      volumes:
        - name: receiver-scripts
          configMap:
            name: l4s-lidar-receiver-scripts
